#!/usr/bin/env python3
"""
Agentic Generator Sandbox & Static Analysis Gatekeeper
======================================================
Implements deterministic ASD ACSC Secure Design checks on AI-generated content
and code before it can be written to disk or deployed to production.

Validates:
1. Prohibited Python AST imports/calls (os.system, subprocess, pty, socket, eval, exec).
2. Anti-AI-Slop and Canned Template rejection (S-CTS standard).
3. Minimum word count and value-dense financial/broker structure.
4. Escaped CSS braces within HTML/CSS templates.
5. PII & Secret scanning.
"""

import re
import ast
from typing import Tuple, List

PROHIBITED_IMPORTS = {"pty", "pickle", "socket", "telnetlib"}
PROHIBITED_FUNCS = {"eval", "exec"}

CANNED_SLOP_SIGNATURES = [
    "The Reserve Bank of Australia and major retail banks have updated residential mortgage assessment benchmarks",
    "In today's rapidly evolving financial landscape",
    "In this fast-paced digital world",
    "As we navigate through the complexities of",
]

SECRET_REGEXES = [
    re.compile(r"sk-[a-zA-Z0-9]{20,}"),
    re.compile(r"ghp_[a-zA-Z0-9]{20,}"),
    re.compile(r"xox[baprs]-[a-zA-Z0-9]{10,}"),
]

def validate_agent_python_code(code_str: str) -> Tuple[bool, List[str]]:
    """
    Statically analyzes Python code generated by an AI agent before execution.
    Returns (is_valid, list_of_errors).
    """
    errors = []

    # 1. Syntax check
    try:
        tree = ast.parse(code_str)
    except SyntaxError as e:
        return False, [f"SyntaxError in generated code at line {e.lineno}: {e.msg}"]

    # 2. Prohibited imports & calls
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name in PROHIBITED_IMPORTS:
                    errors.append(f"Prohibited module import: '{alias.name}'")
        elif isinstance(node, ast.ImportFrom):
            if node.module in PROHIBITED_IMPORTS:
                errors.append(f"Prohibited module import: '{node.module}'")
        elif isinstance(node, ast.Call):
            if isinstance(node.func, ast.Name) and node.func.id in PROHIBITED_FUNCS:
                errors.append(f"Prohibited function execution: '{node.func.id}()'")
            elif isinstance(node.func, ast.Attribute) and node.func.attr == "system":
                errors.append("Prohibited system command execution via 'os.system()'")

    # 3. Secret leaks
    for regex in SECRET_REGEXES:
        if regex.search(code_str):
            errors.append("Potential API key or secret detected in generated code.")

    return len(errors) == 0, errors

def validate_agent_html_article(html_str: str, min_words: int = 250) -> Tuple[bool, List[str]]:
    """
    Validates an HTML/content article generated by an AI agent.
    Enforces minimum word density, anti-slop rules, and escaped CSS braces.
    """
    errors = []

    # 1. Canned slop phrases
    for phrase in CANNED_SLOP_SIGNATURES:
        if phrase.lower() in html_str.lower():
            errors.append(f"Canned boilerplate AI slop detected: '{phrase}'")

    # 2. Word count verification
    clean_text = re.sub(r"<[^>]+>", " ", html_str)
    words = [w for w in clean_text.split() if w.strip()]
    if len(words) < min_words:
        errors.append(f"Article is too thin ({len(words)} words). Minimum requirement is {min_words} words.")

    # 3. Secret leaks
    for regex in SECRET_REGEXES:
        if regex.search(html_str):
            errors.append("Potential API key or credential string found inside generated HTML.")

    # 4. Check for broken or empty title
    if "<title></title>" in html_str or "<title>Untitled" in html_str:
        errors.append("Missing or invalid <title> tag in generated HTML.")

    return len(errors) == 0, errors

if __name__ == "__main__":
    # Self-test with safe and malicious inputs
    sample_safe = """
def calculate_borrowing_capacity(income, expenses):
    return (income - expenses) * 5.5
"""
    sample_malicious = """
import socket
import os
os.system("rm -rf /")
eval("print('injected')")
"""
    valid, errs = validate_agent_python_code(sample_safe)
    assert valid, f"Expected safe code to pass, got: {errs}"

    valid_bad, errs_bad = validate_agent_python_code(sample_malicious)
    assert not valid_bad, "Expected malicious code to be rejected!"
    print("✅ Agentic Generator Sandbox self-tests passed cleanly!")
